config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :orders
  resources :catagory_products, only: [:index, :create]
  resources :products do
    resources :carted_products, only: [:create]
  end

  root to: "products#index"
  get '/carted_products' => 'carted_products#index'
  get '/catagory' => 'catagories#catagory'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/carted_product.rb
class CartedProduct < ApplicationRecord
  belongs_to :order
end

app/models/catagory.rb
class Catagory < ApplicationRecord
  has_many :products
  scope :soap, -> { where(name:'test' )}
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :carted_product
  belongs_to :user

  SALES_TAX = 0.09

  def calculate_subtotal
    return product.price * quantity
  end

  def calculate_tax
    return SALES_TAX * calculate_subtotal
  end

  def calculate_total
    return calculate_subtotal + calculate_tax
end
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  mount_uploader :image, ImageUploader

  belongs_to :catagory
  belongs_to :brand  
  validates_presence_of :name, :image, :inventory
  validates :description, presence: true, length: {minimum: 5, maximum:500}
  validates :price, presence: true, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }

  def catagory_name
   catagory.try(:name)
  end

  def catagory_name=(name)
    self.catagory = Catagory.find_or_create_by(name: name) if name.present?
  end

  def product_catagory(name)
    Catagory.all.where(name: name)

  end

  scope :soap, -> { where(catagory_id: 4)}


  def discount_message
    return "Discount!"
  end
  
  def on_sale_message
    return "On Sale Item!"
  end

  def sale
    if price > 30.00
      return on_sale_message
    else
      return discount_message
    end
  end

  def tax
   return price * 0.09
  end

  def sales_tax
    return tax 
  end

  def total
   return price + tax
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carted_products_controller.rb
class CartedProductsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :authenticate_user!

  def index
    # if user_signed_in?
    @order = Order.find_by( user_id: current_user.id, status: "carted")
    if @order
      @carted_products = @order.carted_products
    else
      flash[:warning] = "There is nothing in your shopping cart."
      redirect_to "/"
    end
  end

  def create
    order = Order.find_by( status: "carted", user_id: current_user.id)
    
    if order
      CartedProduct.create( product_id: params[:product], quantity: params[:quantity], order_id: order.id)
    else
      Order.create( status:  "carted", user_id: current_user.id)
      CartedProduct.create( product_id:  params[:product_id], quantity: params[:quantity], order_id: order.id)
    end
    flash[:success] = "Added to shopping cart!"
    redirect_to '/'
  end

  private

  def cart_params
    params.require(:carted_product).permit(:product_id,
                                      :quantity,
                                      :order_id 
                                     )
  end

end

app/controllers/catagories_controller.rb
class CatagoriesController < ApplicationController
  before_action :set_catagory, only: [:catagory]

  def catagory
    @product_catagory = @catagory.products
  end
  private 

   def set_catagory
    @catagory = Catagory.find_by(:name => params[:name])
    @catagories = Catagory.all
  end    

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    product=product.find(params[:product_id])
    quantity= params[:quantity].to_i
    order = Order.new(quantity:  quantity, user_id: current_user.id, product_id: product_id)
    order.subtotal= order.calculate_subtotal
    order.tax= order.calculate_tax
    order.total=order.calculate_total
    order.save
    flash[:success] = "Thanks for shopping!"
    redirect_to "/products" 
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @soap = Product.soap
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_catagory, only: [:index, :show, :edit, :update, :destroy]

  
  def index
     @products = Product.all
    if params[:filter] == "discount"
      @products = @products.where("price <= ?", 5)
    end
    if params[:sort]
      @products = @products.order(params[:sort] => params[:direction])
    end
    if params[:category]
      category = Category.find_by(:name => params[:category])
      @products = category.products
      # @products = Category.find_by(:name => params[:category]).products
    end
    if params[:search]
        @products= @products.where('name LIKE ?', "%" + params[:search] + "%")
    end
  end

  def show
  end

  def new
    @product= Product.new
  end


  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def edit

  end

  def update
    if @product.update(product_params)
      flash[:success] = "Product was updated successfully!"
      redirect_to product_path(@product)
    else

      render 'edit'
    end  
  end
  
  def destroy
    @product.destroy
    redirect_to root_path
  end


  private
    def set_product
      @product = Product.friendly.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name,
                                      :image,
                                      :description,
                                      :price,
                                      :inventory,
                                      :catagory_id 
                                     )

    end

  def set_catagory
    @catagories = Catagory.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end

  def login_helper style = ''
    if current_user
      link_to "Logout", destroy_user_session_path, method: :delete, class: style
    else
      (link_to "Register", new_user_registration_path , class: style)
      (link_to "Login", new_user_session_path, class: style)
    end
  end

end

app/helpers/carted_products_helper.rb
module CartedProductsHelper
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/catagory_products_helper.rb
module CatagoryProductsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end
  
  def product_img img
    if img.model.image?
      img
    else 
      image_generator(height: '276', width: '183')
    end
  end

end

app/views/carted_products/index.html.erb
<h1>Shopping Cart</h1>
<% @carted_products.each do |carted_product| %>
  <h3><%= carted_product.product.title %></h3>
  <img src="<%= carted_product.product.image %>">
  <h4>Quantity: <%= carted_product.quantity %></h4>
<% end %>

<%= form_tag "/orders/#{@order.id}", :method => :patch do %>
  <%= submit_tag "Complete Purchase!" %>
<% end %>

app/views/catagories/catagory.html.erb
<%= render 'shared/catagory_nav' %>
<% @product_catagory.each do |product| %> 
  <div class="card-deck">
    <div class="card">
      <%= image_tag product.image, class: "card-img-top", alt:"Card image cap" %>
      <div class="card-block">
        <h4 class="card-title"><%=  product.name %></h4>
        <h6> <%= number_to_currency(product.price) %></h6>
        <p class="card-text"><%=  product.description.truncate(20) %></p>
        <p>
          <%= link_to " View More", product_path(product),  class: "btn btn-primary" %>
          <%= link_to " Edit", edit_product_path(product),  class: "btn btn-primary" %>
        </p>
      </div>
    </div>
  </div>  
<% end %>

app/views/layouts/_footer.html.erb
    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p><div class="panel-footer"> ©<%= Time.current.year %> Blue Tulip</div>

    </footer>

app/views/layouts/_messages.html.erb
<div class= "row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        
        <%= msg %>
      </div>  
    <% end %> 
  </div>
</div>   

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-toggleable-md ">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "Nuthin But Soap", root_path, class: "navbar-brand" , style: 'color: black'%>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
       <%= link_to "Home", root_path, class: "nav-link" , style: 'color: black'%>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          On Sale
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Discount Items</a>
          <a class="dropdown-item" href="#">Price: High to Low</a>
          <a class="dropdown-item" href="#">Price: Low to High</a>
        </div>
      </li>


      <li class="nav-item">
        <%= link_to "New Product", new_product_path, class: "nav-link" , style: 'color: black'%>
      </li>
      <li class="nav-item">
        <%= login_helper 'nav-link' %>
      </li>
      <% if current_user && current_user.admin? %>
        <li class="nav-item">
          <%= link_to "Admin", rails_admin_path, class: 'nav-link' %>
        </li>
      <% end %>  
    </ul>
    <%= form_tag products_path, method: :get, class: "form-inline my-2 my-lg-0", role: "search" do %>
      <%=text_field_tag :search, params[:search], class: "form-control mr-sm-2" %>
      <%= submit_tag "Search", name: nil, class: "btn btn-outline-success my-2 my-sm-0" %>
    <%end%>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>NuthinButSoap</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrap">
      <%= render 'layouts/nav' %>
      
      
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

        <%= yield %>
      

      <%= render 'layouts/footer' %>
      
    </div>  
  </body>
</html>

app/views/orders/new.html.erb
<h1>New Order</h1>

<% form_for @order do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= render "#{@order.current_step}_step", f: f %>
  <p><%= f.submit "Continue"%></p>
  <p><%= f.submit "Back", :name => "back_button" unless @order.first_step?%></p>
<% end %>

<%= link_to 'Back', orders_path %>

app/views/pages/home.html.erb
<% @soap.each do |soap|%>
 <div class="card-deck">
    <div class="card">
      <%= image_tag soap.image, class: "card-img-top", alt:"Card image cap" %>
      <div class="card-block">
        <h4 class="card-title"><%=  soap.name %></h4>
        <p class="card-text"><%=  soap.description.truncate(20) %></p>
        <p>
          <%= link_to " View More", product_path(soap),  class: "btn btn-primary" %>
          <%= link_to " Edit", edit_product_path(soap),  class: "btn btn-primary" %>
        </p>
      </div>
    </div>
  </div>  
<% end %>

app/views/products/_catagory_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%#= link_to_remove_association 'Remove Catagory', f %>
</div>

app/views/products/_form.html.erb
<div class = "row"></div>
  <div class= "col-md-12">
    <%= form_for(@product, :html => {class: "form-horizontal", role: "form"}) do |f| %>
         <% if @product.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@product.errors.count, "error") %> prohibited this form from being saved:</h2>

              <ul>
              <% @product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
        <% end %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name, "Enter product" %>
        </div>
        <div class= "col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter your product name", autofocus: true %>
        </div>
      </div> 
      <div class = "form-group">
          <div class ="control-label col-md-2">
        </div>
        <div class= "col-md-8">
          <label class="btn btn-primary">
            Upload a image file <%= f.file_field :image, style: 'display:none;', class: "btn btn-primary btn-lg btn-xlarge"%>
          </label>
        </div>    
      </div> 

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :description, "Enter Description" %>
        </div>
        <div class= "col-md-8">
          <%= f.text_field :description, class: "form-control", placeholder: "Enter your product description", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :price, "Enter price" %>
        </div>
        <div class= "col-md-8">
          <%= f.text_field :price, class: "form-control", placeholder: "Enter the price", autofocus: true %>
        </div>

        <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :inventory, "Enter inventory " %>
        </div>
        <div class= "col-md-8">
          <%= f.text_field :inventory, class: "form-control", placeholder: " Enter available products", autofocus: true %>
        </div>
      </div>

       <div class="form-group">
         <div class="control-label col-md-2">
          <%= f.label :catagory, "Select Category" %>
         </div>
         <div class= "col-md-8">
          <%= f.collection_select :catagory_id, Catagory.order(:name),:id,:name, include_blank: true %>
         </div>
       </div>

      <div class= "form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit(@product.new_record? ? "Create product" : "Update my products", 
              class: "btn btn-primary btn-lg btn-xlarge") %>
        </div> 
      </div>  
    <% end %>
  </div>  
</div>

app/views/products/_jumbotron.html.erb
   
    <section class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">Nuthin But Soap</h>

        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
       
      </div>
    </section>
    <hr>

app/views/products/_productslist.html.erb
<% @products.each do |product| %> 
  <div class="card-deck">
    <div class="card">
      <%= image_tag product.image, class: "card-img-top", alt:"Card image cap" %>
      <div class="card-block">
        <h4 class="card-title"><%=  product.name %></h4>
        <p class="card-text"><%=  product.description.truncate(20) %></p>
        <p>
          <%= link_to " View More", product_path(product),  class: "btn btn-primary" %>
          <%= link_to " Edit", edit_product_path(product),  class: "btn btn-primary" %>
        </p>
      </div>
    </div>
  </div>  
<% end %>

app/views/products/edit.html.erb
<h1> Edit your form </h1>

<%=render 'form' %>
<%= link_to "Delete", @product, method: :delete, data: { confirm: 'Are you sure?'} , class: "btn btn-danger" %>

app/views/products/index.html.erb
<%= render 'jumbotron' %> 

<div class="album text-muted">
  <div class="container">
  <%= render 'shared/catagory_nav' %>
    <div class="row">
      <%= render 'productslist'%>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<h1> Create a new product </h1>
<%=render 'form' %>

app/views/products/show.html.erb
<div class=" container">
  <div class= "row">
    <div class="col-md-7">
      <%= image_tag @product.image, width: '100%' %>
    </div>  
    <div class= "col-md-5">
      <h2><%= @product.name %></h2>
      <p><%= @product.catagory_name %></p>
      <p><%= @product.description %></p>
    </div> 
  </div>
  <hr>

  <table>
    <tr>
      <td>Subtotal:</td>
      <td><%= number_to_currency(@product.price) %></td>
    </tr>
    <tr>
      <td>Tax:</td>
      <td><%= number_to_currency(@product.tax) %></td>
    </tr>
    <tr>
      <td>Total:</td>
      <td><%= number_to_currency(@product.total) %></td>
    </tr>
  </table>
  <%# if user_signed_in? %>
    <%= form_tag "#{@product.slug}/carted_products" do %>
      <%= label_tag :quantity %>
      <%= text_field_tag :quantity %>
      <%= hidden_field_tag :product, @product.id %>

      <%= submit_tag "Add To Cart" %>
    <% end %>
  <%# end %>
</div>

app/views/shared/_catagory_nav.html.erb
<nav class="breadcrumb nav-style">
  <% @catagories.each do |catagory| %>
    <%= link_to "#{catagory.name}",catagory_path(:name =>"#{catagory.name}") %> |
 <% end%>
</nav>